[project]
name = "dxmt-artifact-mirror"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.124.4",
    "notebook>=7.5.0",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
    "sqlmodel>=0.0.27",
]
